expensesapp/urls.py
from django.urls import path
from . import views

app_name = "expensesapp"
urlpatterns = [
    path("", views.home_view, name="home"),
    path("account/", views.account_details_view, name="account_details"),
    path("account/edit/", views.account_edit_view, name="account_edit"),
    path("claims/new/", views.claim_new_view, name="claim_new"),
    path("claims/<str:claim_ref>/", views.claim_details_view, name="claim_details"),
    path("claims/<str:claim_ref>/edit/", views.claim_edit_view, name="claim_edit"),
    path("claims/<str:claim_ref>/delete/", views.claim_delete_view, name="claim_delete"),
    path("claims/<str:claim_ref>/new-receipt", views.receipt_new_view, name="receipt_new"),
    path("receipts/<str:receipt_ref>/", views.receipt_details_view, name="receipt_details"),
    path("receipts/<str:receipt_ref>/edit/", views.receipt_edit_view, name="receipt_edit"),
    path("receipts/<str:receipt_ref>/delete/", views.receipt_delete_view, name="receipt_delete"),
    path("claims/<str:claim_ref>/submit/", views.claim_submit_view, name="claim_submit"),
    path("your-expenses/<str:category>/<int:page_num>/", views.your_expenses_view, name="your_expenses"),
    path("manager/<str:group_url>/<int:page_num>/", views.manager_view, name="manager"),
    path("claims/<str:claim_ref>/return/", views.claim_return_view, name="claim_return"),
    path("claims/<str:claim_ref>/approve/", views.claim_approve_view, name="claim_approve"),
    path("back/", views.back_view, name="back"),
]

expensessite/urls.py
from django.urls import include, path
from django.contrib.auth import views as auth_views
from django.contrib import admin


urlpatterns = [
    path("", include("expensesapp.urls")),
    path('accounts/', include('allauth.urls')),
    path("admin/", admin.site.urls),
]

'''
allauth templates and corresponding URLs:

account_inactive.html               /accounts/inactive
email_confirm.html	                /accounts/confirm-email/
login.html	                        /accounts/login/
logout.html	                        /accounts/logout/
password_reset.html	                /accounts/password/reset/
password_reset_done.html	        /accounts/password/reset/done/
password_reset_from_key.html	    /accounts/password/reset/key/<key>/
password_reset_from_key_done.html   /accounts/password/reset/key/done/
signup.html	                        /accounts/signup/
verification_sent.html	            /accounts/confirm-email/
'''

expensesapp/models.py
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from django.db import models
from django.dispatch import receiver
from django.utils import timezone
from django.utils.dateformat import DateFormat
from django.utils.translation import gettext_lazy as _

from .custom import *


class Currency(models.Model):
    name = models.CharField(max_length=20, unique=True)
    iso_code = models.CharField(max_length=3)
    symbol = models.CharField(max_length=1)
    VAT_NAMES = [("1", "VAT"), ("2", "Sales Tax")]
    vat_name = models.CharField(max_length=1, choices=VAT_NAMES)

    class Meta:
        verbose_name_plural = "currencies"

    def __str__(self):
        return "{} ({})".format(self.name, self.iso_code)


class User(AbstractUser):
    first_name = models.CharField(_('first name'), max_length=150)
    last_name = models.CharField(_('last name'), max_length=150)
    email = models.EmailField(_('email address'), unique=True)
    default_currency = models.ForeignKey("Currency", on_delete=models.CASCADE, default=None, blank=True, null=True)
    primary_manager = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="team_members",
                                        on_delete=models.SET_NULL, default=None, blank=True, null=True)
    substitute = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="other_managers",
                                   on_delete=models.SET_NULL, default=None, blank=True, null=True)
    username = models.CharField(max_length=150,unique=False)
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username", "first_name", "last_name"]
    back_url = models.CharField(max_length=60, default=None, blank=True, null=True)

    def __str__(self):
        return "{0} {1} ({2})".format(self.first_name, self.last_name, self.email)

    def count_claims_by_status(self, status):
        return len(self.claims.filter(status=status))

    def is_manager(self):
        if self.team_members.all() or self.other_managers.all():
            return True
        else:
            return False

    def is_direct_manager(self):
        if self.team_members.all():
            return True
        else:
            return False

    def get_your_teams_pending_claims(self):
        your_teams_claims = None
        for member in self.team_members.all():
            if not your_teams_claims:
                your_teams_claims = member.claims.filter(status="2")
            else:
                your_teams_claims.union(member.claims.filter(status="2"))
        return your_teams_claims

    def get_other_teams_pending_claims(self):
        other_teams_claims = None
        for manager in self.other_managers.all():
            for member in manager.team_members.all():
                if not other_teams_claims:
                    other_teams_claims = member.claims.filter(status="2")
                else:
                    other_teams_claims.union(member.claims.filter(status="2"))
        return other_teams_claims

    def get_all_teams_pending_claims(self):
        your_teams_claims = self.get_your_teams_pending_claims()
        other_teams_claims = self.get_other_teams_pending_claims()
        if your_teams_claims and other_teams_claims:
            return your_teams_claims.union(other_teams_claims)
        elif your_teams_claims:
            return your_teams_claims
        elif other_teams_claims:
            return other_teams_claims
        else:
            return None


class Claim(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="claims", on_delete=models.CASCADE)
    currency = models.ForeignKey("Currency", on_delete=models.CASCADE)
    reference = models.CharField(max_length=8)
    creation_datetime = models.DateTimeField()
    submission_datetime = models.DateTimeField(default=None, blank=True, null=True)
    approval_datetime = models.DateTimeField(default=None, blank=True, null=True)
    approval_manager = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="claims_approved",
                                         on_delete=models.SET_NULL, default=None, blank=True, null=True)
    status_update_datetime = models.DateTimeField()
    description = models.CharField(max_length=50)
    STATUSES = [("1", "Draft"), ("2", "Pending"), ("3", "Sent"), ("4", "Accepted"), ("5", "Rejected")]
    status = models.CharField(max_length=1, choices=STATUSES)

    @classmethod
    def create(cls, owner, currency, description):
        now = timezone.now()
        reference = get_unique_reference(cls, "C")
        status = "1"
        claim = cls(owner=owner, currency=currency, reference=reference, description=description, creation_datetime=now,
                    status=status, status_update_datetime=now)
        return claim

    def submit(self):
        self.status = 2
        now = timezone.now()
        self.submission_datetime = now
        self.status_update_datetime = now

    def return_to_claimant(self, author, feedback_comment):
        self.status = 5
        now = timezone.now()
        self.status_update_datetime = now
        action_desc = "After submission, this claim was rejected and returned to the claimant"
        new_feedback = Feedback.create(now, self, author, feedback_comment, action_desc)
        new_feedback.save()

    def approve(self, manager):
        self.status = 3
        now = timezone.now()
        self.status_update_datetime = now
        self.approval_datetime = now
        self.approval_manager = manager

    def is_editable(self):
        if (self.status == "1") or (self.status == "5"):
            return True
        else:
            return False

    def user_can_view(self, user):
        if self.owner == user:
            return True
        claims_user_can_view = user.get_all_teams_pending_claims()
        if claims_user_can_view:
            if self in claims_user_can_view:
                return True
        return False

    def get_receipts_list_sorted(self):
        return self.receipts.all().order_by("creation_datetime")

    def get_receipts_count(self):
        return len(self.receipts.all())

    def get_total_amount(self):
        total = 0
        for receipt in self.receipts.all():
            total += receipt.amount
        return total

    def get_total_vat(self):
        total = 0
        for receipt in self.receipts.all():
            total += receipt.vat
        return total

    def get_earliest_receipt(self):
        return self.receipts.all().earliest("date_incurred")

    def get_latest_receipt(self):
        return self.receipts.all().latest("date_incurred")

    def get_highest_vat(self):
        receipts = self.receipts.all()
        if len(receipts) == 0:
            return None
        elif len(receipts) == 1:
            receipt = receipts[0]
            return receipt.vat / receipt.amount * 100
        else:
            highest_vat_percent = 0
            for receipt in receipts:

                try:
                    receipt_vat = receipt.vat / receipt.amount * 100
                except ZeroDivisionError:
                    receipt_vat = 0

                if receipt_vat > highest_vat_percent:
                    highest_vat_percent = receipt_vat
            return highest_vat_percent

    def get_latest_feedback(self):
        return self.feedbacks.latest("creation_datetime")

    # Methods that return strings for display:

    def __str__(self):
        return "expenses claim {0}".format(self.reference)

    def get_string_creation_datetime(self):
        return self.creation_datetime

    def get_string_total_amount(self):
        return "{0} {1:0.2f}".format(self.currency.symbol, self.get_total_amount())

    def get_string_total_vat(self):
        return "{0} {1:0.2f}".format(self.currency.symbol, self.get_total_vat())

    def get_string_total_vat_and_percent(self):
        total_vat = self.get_total_vat()
        try:
            percentage = int(round(100 * total_vat / self.get_total_amount()))
            return "{0} {1:0.2f} ({2:d}%)".format(self.currency.symbol, total_vat, percentage)
        except ZeroDivisionError:
            return "{0} {1:0.2f}".format(self.currency.symbol, total_vat)

    def get_string_highest_vat(self):
        return "{0:d}%".format(int(self.get_highest_vat()))

    def get_string_dates_incurred(self):
        try:
            earliest_date = self.get_earliest_receipt().date_incurred
        except AttributeError:
            return None
        latest_date = self.get_latest_receipt().date_incurred
        formatted_earliest_date = DateFormat(earliest_date)
        formatted_latest_date = DateFormat(latest_date)
        if earliest_date == latest_date:
            return "{0}".format(formatted_earliest_date.format("jS M, Y"))
        else:
            if earliest_date.year == latest_date.year:
                if earliest_date.month == latest_date.month:
                    return "{0} – {1}".format(formatted_earliest_date.format("jS"),
                                              formatted_latest_date.format("jS M, Y"))
                else:
                    return "{0} – {1}".format(formatted_earliest_date.format("jS M"),
                                              formatted_latest_date.format("jS M, Y"))
            else:
                return "{0} – {1}".format(formatted_earliest_date.format("jS M, Y"),
                                          formatted_latest_date.format("jS M, Y"))


class Category(models.Model):
    name = models.CharField(max_length=20, unique=True)

    class Meta:
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name


class Receipt(models.Model):
    claim = models.ForeignKey("Claim", related_name="receipts", on_delete=models.CASCADE)
    reference = models.CharField(max_length=10)
    creation_datetime = models.DateTimeField()
    date_incurred = models.DateField()
    category = models.ForeignKey("Category", on_delete=models.CASCADE)

expensesapp/templates/expensesapp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>

    <!-- meta tags required for Bootstrap -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Stylesheets -->
    <link rel="stylesheet" type="text/css" href="{% static "expensesapp/style.css" %}"/>
    <style>#js-area {display: none;}</style>

    <!-- Title -->
    {% block title %}<title>FDM Expenses Portal</title>{% endblock %}

    <!-- Icons -->
    <script type="text/javascript"> (function() { let css = document.createElement('link'); css.href = 'https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.4/css/all.css'; css.rel = 'stylesheet'; css.type = 'text/css'; document.getElementsByTagName('head')[0].appendChild(css); })(); </script>

    <!-- Favicons -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static "expensesapp/images/favicon/apple-touch-icon.png" %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static "expensesapp/images/favicon/favicon-32x32.png" %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static "expensesapp/images/favicon/favicon-16x16.png" %}/">
    <link rel="manifest" href="{% static "expensesapp/images/favicon/site.webmanifest" %}/">

</head>
<body id="standard-body">

<nav class="navbar fixed-top navbar-expand-sm navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url "expensesapp:your_expenses" "all" 1 %}">
            <img src="{% static "expensesapp/images/logo.png" %}" alt="logo" width="68" height="36">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav me-auto mb-2 mb-sm-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url "expensesapp:your_expenses" "all" 1 %}" id="your-expenses-link">
                        HOME
                    </a>
                </li>
                {% if request.user.is_manager %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "expensesapp:manager" "your-team" 1 %}" id="manager-link">
                            MANAGER
                        </a>
                    </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url "expensesapp:account_details" %}" id="account-link">
                        ACCOUNT
                    </a>
                </li>
            </ul>
            <span class="navbar-text">
                FDM Expenses Portal
            </span>
        </div>
    </div>
</nav>

{% if user.is_authenticated %}
    <div class="container overflow-hidden">
        <div class="row justify-content-center" role="alert">
            <div class="col-12 col-lg-9 col-xl-8 col-xxl-7">
                <div class="row justify-content-end align-items-center alert alert-primary gy-2 py-2 px-2">
                    <div class="col px-1">
                        Welcome, <b>{{ user.first_name }} {{ user.last_name }}</b> ({{ user.email }})
                    </div>
                    <div class="col-auto px-1">
                        <a class="btn btn-dark" href="{% url "account_logout" %}">
                            <i class="fas fa-sign-out-alt"></i> Sign Out
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endif %}

{% block content %}{% endblock %}

<div class="container d-none" id="show-on-loading">
    <div class="row justify-content-center mt-5">
        <div class="col-auto mt-5">
            <img src="{% static "expensesapp/images/loading.gif" %}" alt="loading" width="80px" height="80px">
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-auto mt-2">
            <p class="text-muted">Please wait...</p>
        </div>
    </div>
</div>

<!-- JavaScript plugins -->
<script src="{% static "vendor/bootstrap/dist/js/bootstrap.bundle.js" %}"></script>
<script src="{% static "vendor/jquery/jquery-3.6.0.min.js" %}"></script>
<script src="{% static "vendor/jquery/jquery-3.6.0.min.js" %}" crossorigin="anonymous"></script>

<script>

  <!-- Disable form submit buttons upon form submission, to prevent multiple submissions -->
  $("form").submit(function () {
    $(this).find("button[type='submit'],input[type='submit']").prop("disabled", true);
  });

</script>

<!-- Page-specific scripting -->
{% block scripts %}{% endblock %}

<!-- Reveal the slow-to-load form area -->
<script>

  $(document).ready(function () {

    let body_elem = document.getElementById("standard-body");
    body_elem.style.display = "block";

  });

</script>

</body>
</html>

expensesapp/templates/expensesapp/claim_edit.html
{% extends "expensesapp/claim_details.html" %}

{% block back_button %}{% endblock %}

{% block header %}

    <h2>Details <span class="badge bg-warning">Editing</span></h2>

{% endblock %}

{% block form_items %}
    <form id="edit-form" action="{% url "expensesapp:claim_edit" claim.reference %}" method="post">
        {% csrf_token %}
        <div class="row mb-2 gx-5 gy-3">
            <div class="col-12 col-xl-6">
                <dl class="row mb-0">
                    <dt class="col-sm-4">Claimant name</dt>
                    <dd class="col-sm-8">{{ claim.owner.first_name }} {{ claim.owner.last_name }}</dd>
                    <dt class="col-sm-4">Claimant email</dt>
                    <dd class="col-sm-8">{{ claim.owner.email }}</dd>
                    <dt class="col-sm-4">Currency</dt>
                    <dd class="col-sm-8">{{ claim.currency|capfirst }}</dd>
                </dl>
                <dl class="row mb-0 pt-3 pb-2 bg-light border rounded">
                    <dt class="col-sm-4">Status</dt>
                    <dd class="col-sm-8">
                        <span class="badge rounded-pill badge-status bg-status-{{ claim.get_status_display|lower }}">
                            {{ claim.get_status_display }}
                        </span>
                    </dd>
                    <dt class="col-sm-4">Creation date</dt>
                    <dd class="col-sm-8">{{ claim.creation_datetime|date:"D jS M, Y, g:i a" }}</dd>
                    {% if claim.submission_datetime %}
                        <dt class="col-sm-4">Submission date</dt>
                        <dd class="col-sm-8">{{ claim.submission_datetime|date:"D dS M, Y, g:i a" }}</dd>
                    {% endif %}
                    {% if claim.status == "5" %}
                        <dt class="col-sm-4">Rejection date</dt>
                        <dd class="col-sm-8">{{ claim.status_update_datetime|date:"D dS M, Y, g:i a" }}</dd>
                    {% endif %}
                </dl>
            </div>
            <div class="col-12 col-xl-6">
                <dl class="row mb-0">
                    <dt class="col-sm-4">Description</dt>
                    <dd class="col-sm-8 mt-1 mt-sm-0 mb-3">
                        <span class="text-danger"></span>
                        {{ claim_edit_form.description }}
                        {% for error in claim_edit_form.description.errors %}
                            <div class="invalid-feedback">
                                {{ error }}
                            </div>
                        {% endfor %}
                        <div id="description-describer" class="form-text">The description can be up to 50 characters
                            long.
                        </div>
                    </dd>
                    <dt class="col-sm-4">Number of receipts</dt>
                    <dd class="col-sm-8">{{ claim.get_receipts_count }}</dd>
                    {% if claim.receipts.all %}
                        <dt class="col-sm-4">Dates incurred</dt>
                        <dd class="col-sm-8">{{ claim.get_string_dates_incurred }}</dd>
                        <dt class="col-sm-4">Total amount</dt>
                        <dd class="col-sm-8">{{ claim.get_string_total_amount }}</dd>
                        <dt class="col-sm-4">Total {{ claim.currency.get_vat_name_display }}</dt>
                        <dd class="col-sm-8">{{ claim.get_string_total_vat_and_percent }}</dd>
                        <dt class="col-sm-4">Highest {{ claim.currency.get_vat_name_display }} %</dt>
                        <dd class="col-sm-8">{{ claim.get_string_highest_vat }}</dd>
                    {% endif %}
                </dl>
            </div>
        </div>
    </form>

{% endblock %}

{% block edit_buttons %}

    <div class="row">
        <div class="col">
            <div class="row justify-content-end gy-2">
                <div class="col-auto text-nowrap">
                    <a class="btn btn-secondary" href="{% url "expensesapp:claim_details" claim.reference %}">
                        <i class="fas fa-undo symbol-secondary"></i> Discard Changes
                    </a>
                </div>
                <div class="col-auto text-nowrap submit-with-symbol">
                    <i class="fas fa-save text-white"></i>
                    <input class="btn btn-primary text-white" form="edit-form" type="submit" value="Save Changes">
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block add_receipt %}{% endblock %}

{% block receipt_prompt %}{% endblock %}

{% block action_buttons %}{% endblock %}

{% block scripts %}

    <script>

      $(document).ready(function () {

        // Manual override of the 'description' form field to implement Bootstrap formatting
        let description_elem = document.getElementById("{{ claim_edit_form.description.id_for_label }}");
        description_elem.classList.add("form-control");
        description_elem.setAttribute("aria-describedby", "description-describer");
        {% if claim_edit_form.description.errors %}
          description_elem.classList.add("is-invalid");
        {% else %}
          description_elem.classList.add("border-warning");
        {% endif %}

      });

    </script>

{% endblock %}

expensesapp/templates/expensesapp/claim_new.html
{% extends "expensesapp/base.html" %}

{% block content %}

    <div class="container overflow-hidden">
        <div class="row justify-content-center">
            <div class="col col-md-10 col-lg-7 col-xl-6 pb-1 border rounded">
                <div class="row mt-2">
                    <h1>New Expense Claim</h1>
                    <p>Select the currency and enter a description for the new expense claim.</p>
                </div>
                <form action="{% url "expensesapp:claim_new" %}" method="post">
                    {% csrf_token %}

                    <div class="mb-3">
                        <label for="{{ claim_new_form.currency.id_for_label }}" class="form-label">Currency</label>
                        {{ claim_new_form.currency }}
                    </div>

                    <div class="mb-3">
                        <label for="{{ claim_new_form.description.id_for_label }}" class="form-label">
                            Description
                        </label>
                        {{ claim_new_form.description }}
                        {% for error in claim_new_form.description.errors %}
                            <div class="invalid-feedback">
                                {{ error }}
                            </div>
                        {% endfor %}
                        <div id="description-describer" class="form-text">
                            The description can be up to 50 characters long.
                        </div>
                    </div>

                    <div class="row justify-content-end gy-2 mb-2">
                        <div class="col-auto">
                            <a class="btn btn-secondary" href="{% url "expensesapp:home" %}">Cancel</a>
                        </div>
                        <div class="col-auto">
                            <input class="btn btn-primary text-white" type="submit" value="Add Claim">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

{% block scripts %}

    <script>

      $(document).ready(function () {

        // Manual override of the 'currency' form field to implement Bootstrap formatting.
        let currency_elem = document.getElementById("{{ claim_new_form.currency.id_for_label }}");
        currency_elem.classList.add("form-select");

        // Manual override of the 'description' form field to implement Bootstrap formatting
        let description_elem = document.getElementById("{{ claim_new_form.description.id_for_label }}");
        description_elem.classList.add("form-control");
        description_elem.setAttribute("aria-describedby", "description-describer");
        {% if claim_new_form.description.errors %}
          description_elem.classList.add("is-invalid");
        {% endif %}

      });

    </script>

{% endblock %}

expensesapp/templates/expensesapp/receipt_details.html
{% extends "expensesapp/base.html" %}

{% block content %}

    <div class="container overflow-hidden">

        {% block header %}


            <a class="btn btn-light px-2 py-1 my-2" href="{% url "expensesapp:claim_details" receipt.claim.reference %}">
                <i class="fas fa-caret-left"></i> Back to Claim
            </a>
            <h1 class="mb-0">{{ receipt|title }}</h1>
            <hr>
            <h2>Details</h2>

        {% endblock %}

        {% block form_items %}

            <div class="row mb-2 gx-5">
                <div class="col-12 col-xl-6">
                    <dl class="row mb-0">
                        <dt class="col-sm-4">Creation date</dt>
                        <dd class="col-7 col-sm-8">{{ receipt.creation_datetime|date:"D jS M, Y, g:i a" }}</dd>
                        <dt class="col-sm-4">Parent claim</dt>
                        <dd class="col-7 col-sm-8">
                            <a href="{% url "expensesapp:claim_details" receipt.claim.reference %}">
                                {{ receipt.claim|title }}
                            </a>
                        </dd>

                        <dt class="col-sm-4">Date incurred</dt>
                        <dd class="col-7 col-sm-8">{{ receipt.date_incurred|date:"D jS M, Y" }}</dd>
                        <dt class="col-sm-4">Category</dt>
                        <dd class="col-7 col-sm-8">{{ receipt.category }}</dd>
                    </dl>
                </div>
                <div class="col-12 col-xl-6">
                    <dl class="row mb-0">
                        <dt class="col-sm-4">Amount</dt>
                        <dd class="col-7 col-sm-8">{{ receipt.get_string_amount }}</dd>
                        <dt class="col-sm-4">{{ receipt.claim.currency.get_vat_name_display }}</dt>
                        <dd class="col-7 col-sm-8">{{ receipt.get_string_vat }} ({{ receipt.get_string_vat_percent }})
                        </dd>
                        <dt class="col-sm-4">Description</dt>
                        <dd class="col-7 col-sm-8">{{ receipt.description }}</dd>
                    </dl>
                </div>
            </div>

        {% endblock %}
        <div class="accordion mb-3" id="imageAccordion">
            <div class="accordion-item">
                <h2 class="accordion-header" id="headingOne">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne"
                            aria-expanded="false" aria-controls="collapseOne">
                        Image Preview
                    </button>
                </h2>
                <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne"
                     data-bs-parent="#imageAccordion">
                    <div class="accordion-body">
                        {% if receipt.file %}
                            <p class="text-break">{{ receipt.file.name }}</p>
                            <img src="{{ receipt.file.url }}" class="img-fluid" alt="Receipt image">
                        {% else %}
                            <p>There is no image.</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>

        {% block edit_buttons %}

            {% if receipt.claim.is_editable and receipt.claim.owner == request.user %}
                <div class="row justify-content-end gy-2 mb-3">
                    <div class="col-auto text-nowrap">
                        <button type="button" class="btn btn-danger" data-bs-toggle="modal"
                                data-bs-target="#delete-receipt-modal">
                            <i class="fas fa-trash-alt"></i>
                            Delete Receipt
                        </button>
                    </div>
                    <div class="col-auto text-nowrap">
                        <a class="btn btn-primary text-white"
                           href="{% url "expensesapp:receipt_edit" receipt.reference %}">
                            <i class="fas fa-edit"></i> Edit Receipt
                        </a>
                    </div>
                </div>

                <!-- Modal for deleting the receipt -->
                <div class="modal" id="delete-receipt-modal" tabindex="-1" aria-labelledby="delete-receipt-modal-label"
                     aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="delete-receipt-modal-label">Delete Receipt</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                        aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <p>
                                    Are you sure you want to delete
                                    <b>{{ receipt|title }}</b>?
                                </p>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                                <form action="{% url "expensesapp:receipt_delete" receipt.reference %}" method="post">
                                    {% csrf_token %}
                                    {{ receipt_delete_form.receipt }}
                                    <input type="submit" value="Delete" class="btn btn-danger">
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            {% endif %}

        {% endblock %}

    </div>

{% endblock %}